# Site settings
title: Lawrence's Blog
description: Portfolio Website for Lawrence Njume
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lawrence Njume
user_description: I have a background in business and I believe my training in communication and innovation will be invaluable as I grow as a coder. I am interested in automation and deep learning classification problems. I enjoy writing small scripts to leave the repeditive work for the machines and free up others to explore what they enjoy about their career. I'm focusing on becoming an expert in Keras and Redshift an Amazon Web Service.
user_title: Data Scientist
email: lennjume@gmail.com
twitter_username:
github_username: dietmocha
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
